version: '3'

services:
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata management/fixtures/fixtures.json && python manage.py shell < create_superuser.py && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
