# Generated by Django 3.2.25 on 2025-02-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='tenant',
        ),
        migrations.AddField(
            model_name='organization',
            name='tenants',
            field=models.ManyToManyField(related_name='organizations', to='management.Tenant'),
        ),
    ]
