# Generated by Django 3.2.25 on 2025-02-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20250211_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='domain',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
